/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_9db1b392 (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/xchjeirlygncxicdasgd/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

const client = () => createClient(
  Deno.env.get("SUPABASE_URL"),
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),
);

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_9db1b392").upsert({
    key,
    value
  });
  if (error) {
    throw new Error(error.message);
  }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_9db1b392").select("value").eq("key", key).maybeSingle();
  if (error) {
    throw new Error(error.message);
  }
  return data?.value;
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_9db1b392").delete().eq("key", key);
  if (error) {
    throw new Error(error.message);
  }
};

// Alias for backward compatibility
export { del as delete };

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_9db1b392").upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
  if (error) {
    throw new Error(error.message);
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<any[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_9db1b392").select("value").in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_9db1b392").delete().in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
};

// Search for key-value pairs by prefix. Returns only values.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_9db1b392").select("key, value").like("key", prefix + "%");
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};

// Search for key-value pairs by prefix. Returns [key, value] tuples.
export const getByPrefixWithKeys = async (prefix: string): Promise<[string, any][]> => {
  const supabase = client();
  const { data, error } = await supabase.from("kv_store_9db1b392").select("key, value").like("key", prefix + "%");
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => [d.key, d.value] as [string, any]) ?? [];
};

// Delete all key-value pairs by prefix.
export const deleteByPrefix = async (prefix: string): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_9db1b392").delete().like("key", prefix + "%");
  if (error) {
    throw new Error(error.message);
  }
};

// =====================================================
// FUNCIONES EXACTAS PARA FACTURACIÓN Y RUTAS
// =====================================================

export async function getKey(keyArray: string[]) {
  try {
    // @ts-ignore
    const db = await Deno.openKv();
    const result = await db.get(keyArray);
    return result.value;
  } catch (error) {
    console.error("Error en getKey:", error);
    return null;
  }
}

export async function setKey(keyArray: string[], value: any) {
  try {
    // @ts-ignore
    const db = await Deno.openKv();
    await db.set(keyArray, value);
    return true;
  } catch (error) {
    console.error("Error en setKey:", error);
    return false;
  }
}

export async function deleteKey(keyArray: string[]) {
  try {
    // @ts-ignore
    const db = await Deno.openKv();
    await db.delete(keyArray);
    return true;
  } catch (error) {
    console.error("Error en deleteKey:", error);
    return false;
  }
}

// --- ALIAS BLINDADOS (Funciones completas para evitar errores de sintaxis en Deno) ---
export async function getByKey(keyArray: string[]) {
  return await getKey(keyArray);
}

export async function setByKey(keyArray: string[], value: any) {
  return await setKey(keyArray, value);
}

export async function deleteByKey(keyArray: string[]) {
  return await deleteKey(keyArray);
}